stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_REPO: harbor.solutiontech.id:9443
  USER_DOCKER: tdsadmin
  IMAGE_DEV: harbor.solutiontech.id:9443/facerecognition/face-recognition-service-dev
  IMAGE_PROD: harbor.solutiontech.id:9443/facerecognition/face-recognition-service

# === BUILD & DEPLOY PROD (main) ===
build-image:
  stage: build
  only:
    - main
  tags:
    - sigmarunner
  script:
    - echo "Build prod image"
    - docker login $DOCKER_REPO --username $USER_DOCKER --password $PASSWORD_REPO
    - docker build --network host -t "$IMAGE_PROD" .
    - docker push "$IMAGE_PROD"

deploy-image:
  stage: deploy
  only:
    - main
  tags:
    - sigmarunner
  script:
    - echo "Rollout prod"
    - KUBECONFIG=/home/gitlab-runner/kube_tds.yaml kubectl rollout -n tds restart deployment/face-recognition-service
    - KUBECONFIG=/home/gitlab-runner/kube_tds.yaml kubectl rollout -n tds status deployment/face-recognition-service

# === BUILD & DEPLOY DEV (development) ===
build-image-dev:
  stage: build
  only:
    - development
  tags:
    - sigmarunner
  # kalau butuh proxy / env file, bisa tambahin before_script di sini
  script:
    - echo "Build dev image"
    - docker login $DOCKER_REPO --username $USER_DOCKER --password $PASSWORD_REPO
    - docker build --network host -t "$IMAGE_DEV" .
    - docker push "$IMAGE_DEV"

deploy-image-dev:
  stage: deploy
  only:
    - development
  tags:
    - sigmarunner
  script:
    - echo "Rollout dev"
    - KUBECONFIG=/home/gitlab-runner/kube_tds.yaml kubectl rollout -n tds restart deployment/face-recognition-service-dev
    - KUBECONFIG=/home/gitlab-runner/kube_tds.yaml kubectl rollout -n tds status deployment/face-recognition-service-dev
